name: Send message to Telegram

jobs:
  send_message:
    runs-on: ubuntu-latest
      TELEGRAM_CHAT_ID: ${{ inputs.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Post to Telegram
        run: |
          message="[${{ inputs.environment }}] ${{ github.event.repository.name }} - '$(git log -1 --pretty=%B | cat | head -n 1)'"
          curl --request POST \
              --url "https://api.telegram.org/bot${{ inputs.TELEGRAM_BOT_KEY }}/sendMessage" \
              --header 'User-Agent: Telegram Bot SDK - (https://github.com/irazasyed/telegram-bot-sdk)' \
              --header 'accept: application/json' \
              --header 'content-type: application/json' \
              --data "{
            \"text\": \"*$message*\",
            \"disable_web_page_preview\": false,
            \"disable_notification\": false,
            \"reply_to_message_id\": null,
            \"parse_mode\": \"Markdown\",
            \"chat_id\": ${{ inputs.TELEGRAM_CHAT_ID }}
          }"
