name: Send message to Telegram

on:
  workflow_call:
    secrets:
      TELEGRAM_CHAT_ID:
        required: true
      TELEGRAM_BOT_KEY:
        required: true
    inputs:
      ENVIRONMENT:
        type: string
        required: true

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Post to Telegram
        run: |
          message="[${{ inputs.ENVIRONMENT }}] ${{ github.event.repository.name }} - '$(git log -1 --pretty=%B | cat | head -n 1)'"
          curl --request POST \
              --url "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_KEY }}/sendMessage" \
              --header 'User-Agent: Telegram Bot SDK - (https://github.com/irazasyed/telegram-bot-sdk)' \
              --header 'accept: application/json' \
              --header 'content-type: application/json' \
              --data "{
            \"text\": \"*$message*\",
            \"disable_web_page_preview\": false,
            \"disable_notification\": false,
            \"reply_to_message_id\": null,
            \"parse_mode\": \"Markdown\",
            \"chat_id\": ${{ secrets.TELEGRAM_CHAT_ID }}
          }"
